object Form1: TForm1
  Left = 0
  Top = 0
  BorderIcons = [biSystemMenu, biMinimize]
  Caption = 'APS Score calculator'
  ClientHeight = 543
  ClientWidth = 408
  Color = clWhite
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = 'Segoe UI'
  Font.Style = []
  Icon.Data = {
    0000010001002020000001002000A81000001600000028000000200000004000
    0000010020000000000000100000232E0000232E00000000000000000000FFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFEFFF9F9F9FFF8F8F8FFFEFEFEFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFEFEFEFFF5F5F5FFE7E6E5FFE0DEDEFFDDDCDBFFE3E2E2FFEAE9
    E9FFF4F4F4FFFBFBFBFFFDFDFDFFFEFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFCFCFCFFE3E2E1FFD2D0CFFFD6D4D3FFD9D8D7FFD5D3D2FFD4D2
    D1FFD6D4D3FFDAD9D8FFD9D7D7FFE7E6E5FFF6F6F6FFFCFCFCFFFFFFFFFFFFFF
    FFFFFFFFFFFFFEFEFEFFFAFAFAFFFAFAFAFFFEFEFEFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFF8F8F7FFE3E2E1FFD7D5D5FFAAA8A8FF767575FFD0CE
    CEFFD5D3D2FFB2B0AFFF595858FF908F8EFFAFAEADFFA0A09FFFE3E2E2FFBEBE
    BEFFD5D5D5FFFBFBFBFFDFDFDFFFC4C4C4FFA8A8A8FFADADADFFE9E9E9FFCDCD
    CDFFF4F4F4FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFEFEFFF3F3F2FFCECDCCFF4C4B4BFF8C8B
    8AFFD4D2D1FFADABABFF222222FF5E5D5CFF999796FF6B6A69FF9B9A99FF8685
    84FFAAA9A8FFF9F9F9FFFEFDFDFFFCFCFCFFE8E8E8FF5E5E5EFF595959FF6D6D
    6DFFDEDEDEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDFDFCFFC8C7C7FF3A3A
    3AFF696867FF8C8B8AFF252525FFA3A1A1FFA5A3A3FF565555FF5E5D5DFFD1CF
    CEFFD6D4D3FFD8D6D6FFE1E0DFFFF1F0F0FFF7F7F7FF676767FF2E2E2EFFE5E5
    E5FFFEFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFABAB
    ABFF575656FF8D8C8CFF1D1D1DFF757474FFB1AFAEFF7A7978FF222222FF4C4B
    4BFF777675FFB6B4B3FFD5D3D1FFC3C1C0FF5D5D5CFF161616FF8B8B8BFFFEFE
    FEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFB
    FBFF868686FF8C8C8CFF373636FF7A7A79FF8B8A8AFF939291FF3E3D3DFF2626
    26FF141313FF1C1C1BFF797877FF6F6E6DFF121212FF929190FFE6E5E4FFF6F6
    F6FFFDFDFDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFEAEAEAFF575757FF121212FFC2C2C2FFFDFDFDFFDDDDDDFF838383FF5554
    54FF929190FF171616FF030303FF333232FF4B4B4AFF858483FFAFAEADFFC6C4
    C3FFE1E0DFFFF1F0F0FFFCFCFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFD2D2D2FF5A5A5AFFD6D6D6FFFFFFFFFFBDBDBDFF494949FF1515
    15FF353434FF0D0D0DFF000000FF282727FFB9B7B6FFA8A7A6FF8B8A89FFA5A4
    A4FFD9D8D7FFDBDAD9FFEEEDEDFFF9F9F9FFFEFEFEFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFF8F8F8FFFDFDFDFFFFFFFFFFF7F7F7FFB6B6B6FF5B5B
    5BFF2E2E2EFF262626FF4A4A4AFFB3B2B2FFE8E7E7FFDFDEDDFFE5E4E3FFEEED
    EDFFEDEDECFFF1F0F0FFF9F9F9FFF7F6F6FFFAFAFAFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBFB
    FBFFEEEEEEFFE8E8E8FFF6F6F6FFFFFFFFFFFFFFFFFFFCFCFCFFFBFAFAFFFEFE
    FEFFFFFFFFFFFEFEFEFFFEFEFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    0000000000000000000000000000000000000000000000000000000000000000
    000000000000000000000000000000000000000000000000000000000000}
  OnCreate = FormCreate
  TextHeight = 15
  object pnlSelectUNI: TPanel
    Left = 0
    Top = 0
    Width = 408
    Height = 543
    Align = alClient
    TabOrder = 3
    object Label4: TLabel
      Left = 64
      Top = 32
      Width = 275
      Height = 58
      Align = alCustom
      Alignment = taCenter
      Caption = 'Welcome to APS Score calculator'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'Splash'
      Font.Style = [fsBold]
      ParentFont = False
      Transparent = True
      WordWrap = True
    end
    object Label6: TLabel
      Left = 152
      Top = 160
      Width = 105
      Height = 60
      Alignment = taCenter
      Caption = 'Select a University'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Sitka Text'
      Font.Style = [fsUnderline]
      ParentFont = False
      WordWrap = True
    end
    object cmbUNI: TComboBox
      Left = 136
      Top = 240
      Width = 137
      Height = 23
      TabOrder = 0
      Text = '-Select-'
      Items.Strings = (
        'WITS'
        'NWU')
    end
    object BtnUNIselect: TButton
      Left = 263
      Top = 442
      Width = 129
      Height = 41
      Caption = 'NEXT'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -24
      Font.Name = 'Raleway'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 1
      OnClick = BtnUNIselectClick
    end
  end
  object pnlAPSdisplay: TPanel
    Left = 254
    Top = 506
    Width = 408
    Height = 543
    TabOrder = 1
    object lblAPStxt: TLabel
      Left = 39
      Top = 136
      Width = 323
      Height = 29
      Caption = 'YOUR WITS APS IS...'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -27
      Font.Name = 'Splash'
      Font.Style = []
      ParentFont = False
    end
    object lblAPS: TLabel
      Left = 154
      Top = 269
      Width = 94
      Height = 72
      Alignment = taCenter
      Caption = '00'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -67
      Font.Name = 'Splash'
      Font.Style = [fsBold, fsUnderline]
      ParentFont = False
    end
  end
  object pnlWITS_APS: TPanel
    Left = 302
    Top = 489
    Width = 408
    Height = 542
    TabOrder = 0
    object lblHeading: TLabel
      Left = 72
      Top = 32
      Width = 268
      Height = 52
      Align = alCustom
      Alignment = taCenter
      Caption = 'WITS APS SCORE CALCULATOR'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -25
      Font.Name = 'Splash'
      Font.Style = [fsBold]
      ParentFont = False
      Transparent = True
      WordWrap = True
    end
    object lblHeading2: TLabel
      Left = 112
      Top = 170
      Width = 180
      Height = 30
      Alignment = taCenter
      Caption = 'Enter your NSC %'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Sitka Text'
      Font.Style = [fsUnderline]
      ParentFont = False
      WordWrap = True
    end
    object Label1: TLabel
      Left = 232
      Top = 408
      Width = 54
      Height = 15
      Caption = '(Optional)'
    end
    object edtSubject4: TEdit
      Left = 232
      Top = 384
      Width = 97
      Height = 23
      Enabled = False
      TabOrder = 8
      Text = '0'
      OnClick = edtSubject4Click
    end
    object edtMaths: TEdit
      Left = 88
      Top = 232
      Width = 97
      Height = 23
      DoubleBuffered = False
      MaxLength = 3
      NumbersOnly = True
      ParentDoubleBuffered = False
      TabOrder = 0
      Text = 'Maths'
      OnClick = edtMathsClick
    end
    object edtEng: TEdit
      Left = 232
      Top = 232
      Width = 97
      Height = 23
      TabOrder = 1
      Text = 'English'
      OnClick = edtEngClick
    end
    object edtLo: TEdit
      Left = 88
      Top = 285
      Width = 97
      Height = 23
      TabOrder = 2
      Text = 'Life Orientation'
      OnClick = edtLoClick
    end
    object edtOtherLang: TEdit
      Left = 232
      Top = 285
      Width = 97
      Height = 23
      TabOrder = 3
      Text = 'Other Language'
      OnClick = edtOtherLangClick
    end
    object edtSubject1: TEdit
      Left = 88
      Top = 334
      Width = 97
      Height = 23
      TabOrder = 4
      Text = 'Elective Subject'
      OnClick = edtSubject1Click
    end
    object edtSubject2: TEdit
      Left = 232
      Top = 334
      Width = 97
      Height = 23
      TabOrder = 5
      Text = 'Elective Subject'
      OnClick = edtSubject2Click
    end
    object edtSubject3: TEdit
      Left = 88
      Top = 384
      Width = 97
      Height = 23
      TabOrder = 6
      Text = 'Elective Subject'
      OnClick = edtSubject3Click
    end
    object btn8th: TButton
      Left = 232
      Top = 384
      Width = 97
      Height = 23
      Caption = 'Add 8th Subject'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Roboto Thin'
      Font.Style = []
      ParentFont = False
      TabOrder = 7
      WordWrap = True
      OnClick = btn8thClick
    end
    object btnNext: TButton
      Left = 272
      Top = 496
      Width = 129
      Height = 41
      Caption = 'NEXT'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -24
      Font.Name = 'Raleway'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 9
      OnClick = btnNextClick
    end
  end
  object pnlNWU_APS: TPanel
    Left = 342
    Top = 516
    Width = 408
    Height = 542
    TabOrder = 2
    object Label2: TLabel
      Left = 72
      Top = 32
      Width = 269
      Height = 52
      Align = alCustom
      Alignment = taCenter
      Caption = 'NWU APS SCORE CALCULATOR'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -25
      Font.Name = 'Splash'
      Font.Style = [fsBold]
      ParentFont = False
      Transparent = True
      WordWrap = True
    end
    object Label3: TLabel
      Left = 112
      Top = 170
      Width = 180
      Height = 30
      Alignment = taCenter
      Caption = 'Enter your NSC %'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Sitka Text'
      Font.Style = [fsUnderline]
      ParentFont = False
      WordWrap = True
    end
    object Label5: TLabel
      Left = 73
      Top = 496
      Width = 190
      Height = 30
      Caption = 'Life Orientation does not get added for NWU APS calculation'
      WordWrap = True
    end
    object edtMathsNWU: TEdit
      Left = 88
      Top = 232
      Width = 97
      Height = 23
      DoubleBuffered = False
      MaxLength = 3
      NumbersOnly = True
      ParentDoubleBuffered = False
      TabOrder = 0
      Text = 'Maths'
      OnClick = edtMathsNWUClick
    end
    object edtEngNWU: TEdit
      Left = 232
      Top = 232
      Width = 97
      Height = 23
      TabOrder = 1
      Text = 'English'
      OnClick = edtEngNWUClick
    end
    object edtOtherNWU: TEdit
      Left = 232
      Top = 285
      Width = 97
      Height = 23
      TabOrder = 2
      Text = 'Other Language'
      OnClick = edtOtherNWUClick
    end
    object edtEL2NWU: TEdit
      Left = 88
      Top = 334
      Width = 97
      Height = 23
      TabOrder = 3
      Text = 'Elective Subject'
      OnClick = edtEL2NWUClick
    end
    object edtEL1NWU: TEdit
      Left = 88
      Top = 285
      Width = 97
      Height = 23
      TabOrder = 4
      Text = 'Elective Subject'
      OnClick = edtEL1NWUClick
    end
    object edtEL3NWU: TEdit
      Left = 232
      Top = 334
      Width = 97
      Height = 23
      TabOrder = 5
      Text = 'Elective Subject'
      OnClick = edtEL3NWUClick
    end
    object btnNextNWU: TButton
      Left = 272
      Top = 496
      Width = 129
      Height = 41
      Caption = 'NEXT'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -24
      Font.Name = 'Raleway'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 6
      OnClick = btnNextNWUClick
    end
  end
end
